### ISSUE TITLE
error on start

### ISSUE THREAD

**Issue by jww2000** [ghiscoding/Realtime-TODO-Aurelia-Auth-RethinkDB#1]
Im very interested in this, have you seen

``` code
./~/socket.io-client/socket.io.js
Critical dependencies:
1:475-482 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/socket.io-client/socket.io.js 1:475-482

```

**Comment by ghiscoding** [comment]
Yes it's a common thing with `WebPack` and they actually never found a real fix. You can refer to this [Webpack build issues with 1.4.1](https://github.com/socketio/socket.io-client/issues/933) was posted and is still open to date. I even commented myself on that issue.

Nevertheless, this isn't stopping the App from running, it's just a warning message. Everything works as it should.

**Comment by jww2000** [comment]
actually I cant get it to load but it's the previous error, do you know a work around for this?
 Uncaught TypeError: Cannot read property 'accept' of undefined webpack:///./~/bootstrap/dist/css/bootstrap.css?:13

I have a working RC1 skeleton working do I just copy over the modules directory? and make the modification to main.js?

**Comment by ghiscoding** [comment]
Hmm that's strange, this is just a warning on my side and didn't stop me from running the application. Except that it always been a pain in the butt since this was never really fixed, bundling are nice but a little harder to troubleshoot though.

However you are showing an error with `bootstrap.css`, did you check if `Bootstrap` was installed properly?  I would probably have to retry installing, from scratch, this project (and update Aurelia versions). But considering that 2 other people clicked on the star :star: on top. I would assume that they got it working on their side. 

Nonetheless, I'm new to `Aurelia` (didn't do any real project, except this one that I shared) and I'm trying to switch to `Aurelia-CLI`, so I might actually redo this template with CLI instead. Or simply add a `client-cli`.

If you find the error and/or you want to update the Aurelia version to the release version. Please feel free to post a PR. Thank you

**Comment by jww2000** [comment]
thank you fro the response, it's more than just bootstrap, if you comment that out it goes to the next item I believe is fontawesome, so I will try to get it to work, I dont want to try with CLI because of the webpack vs jspm I want to stay with webpack ;)

**Comment by ghiscoding** [comment]
However if you find some issues in my code, please make a PR. Thank you

**Comment by ghiscoding** [comment]
I looked at it in the weekend and I actually got the same errors as you had. Not sure why I was able to run it in the past, but anyhow I modified some code and also updated to latest `Aurelia` release and it's all good now. 

So please give it another try and let me know.
